# Site settings
title: Gregory Rearden's Portfolio
description: Gregory Rearden's development portfolio. Contains experience and projects.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://gregoryrearden.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gregory Rearden
user_description: I am a Front End Developer living in Dayton, OH. Web Development is not only a job to me, it is also a passion. I take pride in my listening skills where I can examine all of the elements and find a working solution to a problem. I am eager to tackle constantly evolving adventures in the field of web development.
user_title: Web Developer
email: powerfulech0development@gmail.com
github_username:  powerfulech0

# Google-analytics
google-analytics:
  id: "UA-116160978-1"

plugins:
  - jekyll-seo-tag

exclude: ['package.json', 'src' , 'node_modules']
